=== sergiovj2001/sergiovj2001.github.io/lm/xmldiscord/personas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="personat" type="datosPersona"
                              maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="datosPersona">
      <xs:sequence>
          <xs:group ref="datosBasicos"/>
          <xs:element name="telefono" type="xs:string"/>
        </xs:sequence>  
</xs:complexType>


  <xs:group name="datosBasicos">
      <xs:sequence>
          <xs:element name="nombre"  type="xs:string"/>
          <xs:element name="edad" type="xs:positiveInterger"/>
          <xs:element name="pais" type="xs:string"/>
        </xs:sequence>
  </xs:group>
</xs:complexType>
</xs:schema>

=== sergiovj2001/sergiovj2001.github.io/lm/xmldiscord/personas.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="personas.xsd">
  <persona>
  <nombre>Eva</nombre>
  <edad>25</edad>
  <pais>Francia</pais>
  <telefono>999888777</telefono>
</persona>
<persona>
  <nombre>Giorno</nombre>
  <edad>15</edad>
  <pais>Italia</pais>
  <telefono>11122233</telefono>
</persona>
</personas>
